name: Download, process and save DrugBank KG

on:
  workflow_dispatch:

jobs:
  download_and_extract:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create data directory
        run: New-Item -ItemType Directory -Path data
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download latest DrugBank release
        run: |
          $username = ${{ secrets.DRUGBANK_EMAIL }}
          $password = ${{ secrets.DRUGBANK_PASSWORD }}
          $url = "https://go.drugbank.com/releases/5-1-12/downloads/all-full-database"
          $output = "filename.zip"
        
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)
        
          Invoke-WebRequest -Uri $url -Credential $credential -OutFile $output
          shell: pwsh
        
      - name: Extract DrugBank data
        run: Expand-Archive -Path filename.zip -DestinationPath data
      # - name: Extract DrugBank data
      #   run: |
      #     unzip -o filename.zip -d ./data/
      # - name: Install dependencies
      #   run: |
      #     pip install rdflib agraph-python lxml python-dotenv
      # - name: Run the Python script
      #   env: 
      #      AGRAPH_HOST: ${{ secrets.AGRAPH_HOST }}
      #      AGRAPH_PORT: ${{ secrets.AGRAPH_PORT }}
      #      AGRAPH_USER: ${{ secrets.AGRAPH_USER }}
      #      AGRAPH_PASSWORD: ${{ secrets.AGRAPH_PASSWORD}}
      #   run: |
      #     python extract_and_create.py
